### Base local planner params
#

TrajectoryPlannerROS:
   # Robot configuration parameters, these are the velocity limit of this robot
   max_vel_x: 1.0
   min_vel_x: 0.1
   
   # Angular velocity limits
   max_vel_theta: 2.0
   min_vel_theta: -2.0
   min_in_place_vel_theta: 0.5
   
   # These are the acceleration limits of the robot
   acc_lim_x: 1.0
   acc_lim_theta: 1.0
   
   # Goal tolerance parameters: the tolerance of robot when it reach the goal position
   yaw_goal_tolerance: 0.3
   xy_goal_tolerance: 0.15
   
   # Forward simulation parameters
   sim_time: 3.0
   vx_samples: 6
   vtheta_samples: 20
   
   # Trajectory scoring parameters
   meter_scoring: true
   pdist_scale: 0.6
   gdist_scale: 0.8
   occdist_scale: 0.01
   heading_lookahead: 0.325
   dwa: true
   
   # Oscillation prevention parameters
   oscillation_reset_dist: 0.05
   
   # Differential-drive robot configuration: if the robot is holonomic configuration,
   # set to true other vice set to false. Gribot is a non holonomic robot.
   holonomic_robot: false
   max_vel_y: 0.0
   min_vel_y: 0.0
   acc_lim_y: 0.0
   vy_samples: 1
   