### Common fonfiguration local_costmap and local_costmap

# Contains the parameters common to global and local costmap

# The maximum value of height wich has to be taken as an obstacle
max_obstacle_height: 0.80

# This parameter set the maximum obstacle range. In this cas, the robot will only
# look at obstacle within this distence in front of him
obstacle_range: 2.5  # in m

# This parameter helps the robot to clear out space in front of it upto
# that distance
raytrace_range: 3.0  # in m

# Robot footprint
footprint: [[-0.4,-0.4],[-0.4,0.4],[0.4,0.4],[0.4,-0.4]]

# This parameter will actually inflate the obstacle range up to thi s distance from
# the actual obstacle. This can be taken as a tolerance value of the obstacle
inflation_radius: 0.50  # in m

# This parameter is used for computing cost during inflation
cost_scaling_factor: 7

# We can either choose map type as voxel which will give a 3D view of the
# world, or the other type, costmap which is a 2D view of the map.
map_type: costmap

# This is the z_origin of the map if it is voxel
origin_z: 0.0

# z resolution of map in meters
z_resolution: 0.2

# No of voxels in a vertical column
z_voxels: 2

# This flag set wheter we need map for visualisation purpose
publish_voxel_map: false

# A list of observation source in which we get scan data and its parameters
observation_source: laser_scan_sensor

laser_scan_sensor:
   {
    sensor_frame: sweep_link, 
    data_type: LaserScan,
    topic: /base_scan,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.0,
    max_obstacle_height: 1.0   
    }
    


