#!/bin/bash
#
# This script initialize socketCAN.
# It is based on the ssumption that
# CAN drivers are automatically
# loaded at boot time.
#

# set -x

echo "Initialize SocketCAN"

sudo slcand -o -c -f -s4 /dev/canbus can0
sleep 2
sudo ifconfig can0 up
